title: Haruto's Page
theme: minima

# ナビゲーションリンクを生成しない
header_pages: []

# Markdown設定（必要に応じて）
markdown: kramdown

# GitHub Pages用（必要なら）
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji